### ISSUE TITLE
HOME : Key Features

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#34]
1. The text content for each box is not uniform. Hence, does not look aligned
2. https://aws.amazon.com/iot/ -- the way the IoT services are added can be a good reference.
3. The text alignment is not good in each box. Please update it.
4. Because, we added only 2 per row, lot of blank spaces and scroll multiple to get a complete view. Can we make it smaller, better spaced, boxed and make 3 per row?

**Comment by anvithks** [comment]
1. To make the text uniform the content has to be written with the same number of words / characters.   
2. Can make it like this. please provide me with approved text that is of the same length for all. 
3. Ok will check this after the text is updated.
4. There are 8 key features. I can do 4 and 4 instead of 3. But with lesser text the 2 column structure may also look good. Scroll will be there in this design.

**Comment by stevenphtan** [comment]
i'll take care of of rewriting the tex and ariel is redesigning with 4 columns as the current columns are too narrow.

**Comment by anvithks** [comment]
@stevenphtan @skdwriting I have updated the Key features as per Ariel's design.
[https://sodafoundation.io/#key-features](https://sodafoundation.io/#key-features)

**Comment by anvithks** [comment]
This is done.
