### ISSUE TITLE
HOME: Supporters, CopyRight info

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#36]
1. The scroller view is not good. At times, it creates lot of black space in while viewing (esp after Toyota!!) 
2. Instead of Supporters, can we call them as SODA Collaborators OR SODA Partner Ecosystem ?
3. Please add all the supporting organizations logo in the list. Currently it looks very less companies!!! Even our ecosystem supporting organizations logo(based on their agreement), we can add. It will be useful!!!
4. Instead of Support SODA (looks like charity support!!) -- "Join SODA" is better?
5. Copy right info alignment is not proper...waste of space in the home...Put it at the lowest possible place and alingn across the width. Also it must be responsive!
6. Some logos are not HD. Better to use svg ?

**Comment by stevenphtan** [comment]
1. agree, last one has a long pause. can we make it scroll smoothly one by one as opposed to this slider format?
2. definitely not collaborators.  We should use as per charter definition, either Supporters or Members. Partners maybe ok too but that term is more enterprise
3. Agree and done I think
4. Changed to Become A Member

**Comment by anvithks** [comment]
1. Since there were only 5 logos  the particular carousel was waiting to show all (up until the last one) before changing page, in this case going back to start. Now, since we are showing all supporter logos, the scroll is much smoother. 
2. Going with Supporters for now. Let me know if it needs to be changed.
3. Added all logos that were approved by Larry. He asked to remove a few as they had not signed the agreement. Let me know if any are missing. I will add.
4. Changed.
5. Alignment is fixed. Please let me know if it is still breaking on your screen.
6. I have used svg where I could find. Some company logos svg files were not available. I will let Larry know which ones and try to procure the svg logos. 
@skdwriting @stevenphtan

**Comment by anvithks** [comment]
This is more or less done. If any minor issues remain they can be raised separately. Closing for now.
